service: seisms-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  timeout: 60
  stage: ${self:custom.stage}
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  versionFunctions: false
  environment:
    ${file(${self:custom.stage}.env.json)}
  logs:
    restApi: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:GetBucketLocation'
          Resource:
            - arn:aws:s3:::*
        - Effect: 'Allow' 
          Action:
          - 's3:ListBucket'
          - 's3:PutObject'
          - 's3:PutObjectAcl'
          - 's3:GetObject'
          Resource:
            - arn:aws:s3:::seisms-bucket/*
            - arn:aws:s3:::seism-bucket-results/*
        - Effect: 'Allow'
          Action:
          - 'logs:CreateLogStream'
          - 'logs:CreateLogGroup'
          - 'logs:PutLogEvents'
          Resource: '*'
        - Effect: 'Allow'
          Action:
          - 'athena:*'
          Resource: '*'
        - Effect: 'Allow'
          Action:
          - 'glue:GetTable'
          Resource:
            - 'arn:aws:glue:us-east-1:502666848621:catalog'
            - 'arn:aws:glue:us-east-1:502666848621:database/seisms_database/*'

layers:
  seismsdependencies:
    path: layers/seismsdependencies
    description: Python dependencies for Seisms
    retain: false
    compatibleRuntimes:
      - python3.10
    compatibleArchitectures:
      - "arm64"
      - "x86_64"

package:
  patterns:
    - '!*'
    - '!seed/**'
    - 'src/**'

functions:
  get-entries:
    handler: src/seisms_handler.get_seisms
    layers:
      - !Ref SeismsdependenciesLambdaLayer
    events:
      - http:
          path: seisms
          method: get
          request:
            parameters:
              querystrings:
                country: false
                dateLower: false
                dateUpper: false
                magnitudeLower: false
                magnitudeUpper: false
                skip: false
  create-entries:
    handler: src/seisms_handler.create_seisms
    layers:
      - !Ref SeismsdependenciesLambdaLayer
    events:
      - http:
          path: seisms
          method: post
          request:
            schemas:
              application/json: ${file(src/models/seisms_create_entries_schema.json)}

custom:
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:provider, 'serverless-deploy-seisms-prod'}
  serverless-offline:
    useChildProcesses: true
  layers:
      - !Ref SeismsdependenciesLambdaLayer

resources:
  Resources:
    SeismEntries:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: seisms-bucket
