service: seisms-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  timeout: 60
  stage: ${self:custom.stage}
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  versionFunctions: false
  environment:
    ${file(${self:custom.stage}.env.json)}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:'PutObject'
          Resource:
            - arn:aws:s3:::seisms-bucket/*

layers:
  seismsdependencies:
    path: layers/seismsdependencies
    description: Python dependencies for Seisms
    retain: false
    compatibleRuntimes:
      - python3.10
    compatibleArchitectures:
      - "arm64"
      - "x86_64"

package:
  patterns:
    - '!*'
    - '!seed/**'
    - 'src/**'

functions:
  get-entries:
    handler: src/seisms_handler.get_seisms
    events:
      - http:
          path: seisms
          method: get
          request:
            parameters:
              querystrings:
                url: true
  create-entries:
    handler: src/seisms_handler.create_seisms
    events:
      - http:
          path: seisms
          method: post

custom:
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:provider, 'serverless-deploy-seisms-prod'}
  serverless-offline:
    useChildProcesses: true
  layers:
      - !Ref SeismsdependenciesLambdaLayer

resources:
  Resources:
    SeismEntries:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: seisms-bucket
  