service: seisms-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    ${file(.env_config/${self:custom.stage}.env.json)}

layers:
  odoodependencies:
    path: layers/seismsdependencies
    description: Python dependencies for Seisms
    retain: false
    compatibleRuntimes:
      - python3.10
    compatibleArchitectures:
      - "arm64"
      - "x86_64"

package:
  patterns:
    - '!*'
    - '!seed/**'
    - 'src/**'

functions:
  get-entries:
    handler: src/seisms_handler.get_seisms
    events:
      - http:
          path: seisms
          method: get
          request:
            parameters:
              querystrings:
                url: true
  create-entries:
    handler: src/seisms_handler.create_seisms
    events:
      - http:
          path: seisms
          method: post

custom:
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-2'}
  profile: ${opt:provider, 'serverless-deploy-seisms-prod'}
  serverless-offline:
    useChildProcesses: true

resources:
  Resources:
    SeismEntries:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: seisms-bucket
  